### ISSUE TITLE
git clone... is giving me a syntax error

### ISSUE THREAD

**Issue by trckl** [digital-scrappy/network-analysis-hackathon#18]
I tried to clone the repository but I got a syntax error with the command
![error](https://user-images.githubusercontent.com/117453002/199973257-7917fdff-a069-4c70-bb1b-9c2251f941f2.PNG)

**Comment by timo-damm** [comment]
I did not have this issue (see below) maybe it is an issue on your machine rather than the syntax? 
![image](https://user-images.githubusercontent.com/108958755/199974095-6e12c87c-e0f4-44fa-89fd-9498062f4785.png)

**Comment by trckl** [comment]
Hey,
Thank you for the feedback.

Tried uninstalling all, then installing again. Same errror. :/  Will try googling it.

EDIT:
I didn't have Git installed.... Works fine now. ☺

**Comment by timo-damm** [comment]
Good to hear!
